using System;
using System.Collections.Generic;

namespace Bookish.Models.Repository
{
    public static class RandomData
    {
        private static Random gen = new Random();

        public static DateTime RandomDate() {
            DateTime start = new DateTime(1995, 1, 1);
            int range = (DateTime.Today - start).Days;           
            return start.AddDays(gen.Next(range));
        }
        
        public static List<string> titles = new List<string>()
        {
            "Jack and the Ben stalk",
            "Ben goes to school",
            "Ben on the moon",
            "Oxford dictionary of Ben",
            "The Chronicles of Ben",
            "Romeo and Ben",
            "Ben and Juliet",
            "Ben and Ben",
            "Ben and the Teddy bear",
            "Learn c#",
            "Learn Javascript",
            "IBen",
            "The devil wears Ben",
            "The art of war",
            "BenJammer",
            "Diaries from the roof",
            "Of Mice and Ben",
            "Brave new Ben",
            "Breaking Ben",
            "Ben of the Flies",
            "Ben and the Willows",
            "Bennby",
            "Ben's last day at work",
            "The greatest Show man (Ben)",
            "Hound of the BenSkilviles",
            "The final countdown",
            "Animal farm",
            "The apprentices",
            "Bears and wolves",
            "My favourite shoe",
            "Temuujin sleeps",
            "Temuujin's adventure on the roof"
        };
        public static List<string> genres = new List<string>()
        {
            "Horror",
            "Romance",
            "Comedy",
            "Children",
            "History",
            "Religious",
            "Mystery",
            "Short stories",
            "Thrillers",
            "Biography",
            "Cook books",
            "Memoir",
            "Poetry",
            "Self help",
            "True crime"
        };
        public static List<string> names = new List<string>()
        {
            "Olivia Doe",
            "Emma Alexis",
            "Ava Fernandes",
            "Charlotte Joes",
            "Sophia Skahes",
            "Amelia Blake",
            "Isabella Snake",
            "Mia Elephant",
            "Evelyn Doggo",
            "Harper Subwoofer",
            "Camila Doe",
            "Gianna Alexis",
            "Abigail Fernandes",
            "Luna Joes",
            "Ella Skahes",
            "Elizabeth Blake",
            "Sofia Snake",
            "Emily Elephant",
            "Avery Doggo",
            "Mila Subwoofer",
            "Scarlett Doe",
            "Eleanor Alexis",
            "Madison Fernandes",
            "Layla Joes",
            "Penelope Skahes",
            "Aria Blake",
            "Chloe Snake",
            "Grace Elephant",
            "Ellie Doggo",
            "Nora Subwoofer",
            "Hazel Doe",
            "Zoey Alexis",
            "Riley Fernandes",
            "Victoria Joes",
            "Lily Skahes",
            "Aurora Blake",
            "Violet Snake",
            "Nova Elephant",
            "Hannah Doggo",
            "Emilia Subwoofer",
            "Zoe Doe",
            "Stella Alexis",
            "Everly Fernandes",
            "Isla Joes",
            "Leah Skahes",
            "Lillian Blake",
            "Addison Snake",
            "Willow Elephant",
            "Lucy Doggo",
            "Paisley Subwoofer",
            "Liam Doe",
            "Noah Alexis",
            "Oliver Fernandes",
            "Elijah Joes",
            "William Skahes",
            "James Blake",
            "Benjamin Snake",
            "Lucas Elephant",
            "Henry Doggo",
            "Alexander Subwoofer",
            "Mason Doe",
            "Michael Alexis",
            "Ethan Fernandes",
            "Daniel Joes",
            "Jacob Skahes",
            "Logan Blake",
            "Jackson Snake",
            "Levi Elephant",
            "Sebastian Doggo",
            "Mateo Subwoofer",
            "Jack Doe",
            "Owen Alexis",
            "Theodore Fernandes",
            "Aiden Joes",
            "Samuel Skahes",
            "Joseph Blake",
            "John Snake",
            "David Elephant",
            "Wyatt Doggo",
            "Matthew Subwoofer",
            "Luke Doe",
            "Asher Alexis",
            "Carter Fernandes",
            "Julian Joes",
            "Grayson Skahes",
            "Leo Blake",
            "Jayden Snake",
            "Gabriel Elephant",
            "Isaac Doggo",
            "Lincoln Subwoofer",
            "Anthony Doe",
            "Hudson Alexis",
            "Dylan Fernandes",
            "Ezra Joes",
            "Thomas Skahes",
            "Charles Blake",
            "Christopher Snake",
            "Jaxon Elephant",
            "Maverick Doggo"
        };
    }
}